/*
 * About.java
 *
 * Created on __DATE__, __TIME__
 */

package me.lazynight.stusys.view;

import java.awt.Image;
import java.io.IOException;

import javax.imageio.ImageIO;

/**
 * 
 * @author __USER__
 */
public class About extends javax.swing.JDialog {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5937206172751382464L;
	
	/** Creates new form About */
	public About(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		setLocationRelativeTo(null);
		// …Ë÷√icon
		try {
			String src = "/img/users.png";
			Image image = ImageIO.read(this.getClass().getResource(src));
			this.setIconImage(image);
		} catch (IOException e) {
			e.printStackTrace();
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("About");

		jLabel1.setFont(new java.awt.Font("∫⁄ÃÂ", 1, 36));
		jLabel1.setText("\u5b66\u751f\u4fe1\u606f\u7ba1\u7406\u7cfb\u7edf");

		jLabel2.setText("by\u4e8e\u54f2");

		jLabel3.setText("Blog\uff1ahttp://lazynight.me");

		jLabel4.setText("Date:2013/4/26");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(24, 24, 24)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel4)
												.addComponent(jLabel3)
												.addComponent(jLabel1))
								.addContainerGap(63, Short.MAX_VALUE))
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(345, Short.MAX_VALUE)
								.addComponent(jLabel2)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel1)
								.addGap(18, 18, 18)
								.addComponent(jLabel3)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jLabel4)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										22, Short.MAX_VALUE)
								.addComponent(jLabel2)));

		pack();
	}// </editor-fold>
		// GEN-END:initComponents



	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	// End of variables declaration//GEN-END:variables

}