/*
 * Login.java
 *
 * Created on __DATE__, __TIME__
 */

package me.lazynight.stusys.view;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.imageio.ImageIO;
import javax.swing.JFrame;

import me.lazynight.stusys.entity.User;
import me.lazynight.stusys.service.*;

/**
 *
 * @author  __USER__
 */
public class Login extends javax.swing.JFrame {

	/** Creates new form Login */
	public Login() {
		initComponents();
		//设置icon
		try {
			String src = "/img/users.png";
			Image image = ImageIO.read(this.getClass().getResource(src));
			this.setIconImage(image);
		} catch (IOException e) {
			e.printStackTrace();
		}
		//		//居中
		//		Dimension screensize = Toolkit.getDefaultToolkit().getScreenSize();
		//		Dimension framesize  = this.getSize();     
		//	    int x = (int)screensize.getWidth()/2 - (int)framesize.getWidth()/2;     
		//	    int y = (int)screensize.getHeight()/2 - (int)framesize.getHeight()/2;     
		//	    this.setLocation(x,y);
		setLocationRelativeTo(null);
		//禁止最大化
		this.setResizable(false);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel3 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		btnLogin = new javax.swing.JButton();
		btnExit = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		txtName = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		txtPwd = new javax.swing.JPasswordField();
		lblMeg = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u5b66\u751f\u4fe1\u606f\u7ba1\u7406\u7cfb\u7edf");

		jLabel3.setFont(new java.awt.Font("微软雅黑", 1, 24));
		jLabel3.setText("\u5b66\u751f\u4fe1\u606f\u7ba1\u7406\u7cfb\u7edf");

		jLabel2.setText("\u5bc6\u7801\uff1a");

		btnLogin.setToolTipText("\u767b\u9646");
		btnLogin.setLabel("\u767b\u9646");
		btnLogin.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnLoginActionPerformed(evt);
			}
		});

		btnExit.setToolTipText("\u53d6\u6d88");
		btnExit.setLabel("\u53d6\u6d88");
		btnExit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnExitActionPerformed(evt);
			}
		});

		jLabel1.setText("\u7528\u6237\u540d\uff1a");

		txtName.setToolTipText("\u8bf7\u8f93\u5165\u7528\u6237\u540d");

		jLabel4.setText("by\u4e8e\u54f2");

		txtPwd.setToolTipText("\u8bf7\u8f93\u5165\u5bc6\u7801");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		48,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(
																		jLabel3,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		219,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel2)
																				.addComponent(
																						jLabel1))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addComponent(
																						txtPwd,
																						javax.swing.GroupLayout.Alignment.LEADING,
																						0,
																						0,
																						Short.MAX_VALUE)
																				.addComponent(
																						txtName,
																						javax.swing.GroupLayout.Alignment.LEADING,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						183,
																						Short.MAX_VALUE)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										btnLogin)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																										65,
																										Short.MAX_VALUE)
																								.addComponent(
																										btnExit)))
																.addGap(26, 26,
																		26)))
								.addGap(41, 41, 41))
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addGap(72, 72, 72)
								.addComponent(lblMeg,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										181, Short.MAX_VALUE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jLabel4).addGap(14, 14, 14)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel3)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(35, 35,
																		35)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jLabel1)
																				.addComponent(
																						txtName,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jLabel2)
																				.addComponent(
																						txtPwd,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGap(18, 18,
																		18)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						btnLogin)
																				.addComponent(
																						btnExit))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		lblMeg,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		14,
																		Short.MAX_VALUE)
																.addContainerGap())
												.addGroup(
														layout.createSequentialGroup()
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jLabel4)))));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {
		System.exit(0);
	}

	private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String username = txtName.getText().trim();
		String password = txtPwd.getText().trim();
		if (username.isEmpty() || password.isEmpty()) {
			lblMeg.setText("请输入用户名和密码");
		} else {
			lblMeg.setText("");
			final ServiceFacade sf = new ServiceFacade();
			List<User> list = new ArrayList<User>();
			list = sf.selectUser(username,password);
			if(list.isEmpty()){
				lblMeg.setText("用户名密码错误");
			}else{
				/*
				 * 1学生 2教师 3管理员
				 * */
				int prino = list.get(0).getPrino();
				Man_Index mi = new Man_Index(prino);
				mi.setVisible(true);
				this.setVisible(false);
			}
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Login().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnExit;
	private javax.swing.JButton btnLogin;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel lblMeg;
	private javax.swing.JTextField txtName;
	private javax.swing.JPasswordField txtPwd;
	// End of variables declaration//GEN-END:variables

}