/*
 * Man_Users.java
 *
 * Created on __DATE__, __TIME__
 */

package me.lazynight.stusys.view;

import me.lazynight.stusys.service.*;
import me.lazynight.stusys.entity.User;
import me.lazynight.stusys.entity.ViewUser;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import javax.management.modelmbean.ModelMBean;

/**
 *
 * @author  __USER__
 */
public class Man_Users extends javax.swing.JPanel {

	/** Creates new form Man_Users */
	public Man_Users() {
		initComponents();
		getViewUserList();
	}

	private void getViewUserList() {
		ServiceFacade sf = new ServiceFacade();
		List<ViewUser> list = new ArrayList<ViewUser>();
		list = sf.getViewUserList();
		//table
		Object rowData[][] = new Object[list.size()][3];
		String column[] = { "用户名", "口令", "权限" };
		tb_user = new javax.swing.JTable(rowData, column);
		jScrollPane1.setViewportView(tb_user);

		int i = 0;
		Iterator it = list.iterator();
		while (it.hasNext()) {
			ViewUser vu = (ViewUser) it.next();
			System.out.println(vu);
			rowData[i][0] = vu.getUsername();
			rowData[i][1] = vu.getPassword();
			rowData[i][2] = vu.getPriname();
			i++;
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tb_user = new javax.swing.JTable();
		jPanel2 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		txtUserName = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		btnInsert = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		btnRefresh = new javax.swing.JButton();

		tb_user.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] {

				}, new String[] { "用户名", "口令", "权限" }) {
			boolean[] canEdit = new boolean[] { false, false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jScrollPane1.setViewportView(tb_user);

		jLabel1.setText("\u7528\u6237\u540d\uff1a");

		jButton1.setText("\u67e5\u8be2");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		btnInsert.setText("\u63d2\u5165");
		btnInsert.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnInsertActionPerformed(evt);
			}
		});

		jButton3.setText("\u5220\u9664");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jButton4.setText("\u66f4\u65b0");

		btnRefresh.setText("\u5237\u65b0");
		btnRefresh.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnRefreshActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												jLabel1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												55,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												txtUserName,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												105,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(btnInsert)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton3)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton4)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												33, Short.MAX_VALUE)
										.addComponent(
												btnRefresh,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												60,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap()));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(
																txtUserName,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jButton1)
														.addComponent(btnInsert)
														.addComponent(jButton3)
														.addComponent(jButton4)
														.addComponent(
																btnRefresh))
										.addContainerGap()));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(jScrollPane1,
						javax.swing.GroupLayout.Alignment.TRAILING,
						javax.swing.GroupLayout.DEFAULT_SIZE, 555,
						Short.MAX_VALUE));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout
										.createSequentialGroup()
										.addComponent(
												jPanel2,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												292,
												javax.swing.GroupLayout.PREFERRED_SIZE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.PREFERRED_SIZE));
	}// </editor-fold>
	//GEN-END:initComponents

	//查询指定username用户
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String username = txtUserName.getText().trim();
		List<ViewUser> list = new ArrayList<ViewUser>();
		ServiceFacade sf = new ServiceFacade();
		list = sf.getSelectViewUser(username);
		System.out.println(list);
		
		this.remove(tb_user);
		Object rowData[][] = new Object[list.size()][3];
		String column[] = { "用户名", "口令", "权限" };
		tb_user = new javax.swing.JTable(rowData, column);
		jScrollPane1.setViewportView(tb_user);
		int i = 0;
		Iterator it = list.iterator();
		while (it.hasNext()) {
			ViewUser vu = (ViewUser) it.next();
			System.out.println(vu);
			rowData[i][0] = vu.getUsername();
			rowData[i][1] = vu.getPassword();
			rowData[i][2] = vu.getPriname();
			i++;
		}
	}
	//刷新列表
	private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		getViewUserList();
	}
	
	//删除指定用户
	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		int row = tb_user.getSelectedRow();
		if (row != -1) {
			System.out.println("当前行：" + row);
			String username = tb_user.getValueAt(row, 0).toString();
			System.out.println("要删除"+username);
			ServiceFacade sf = new ServiceFacade();
			sf.deleteUser(username);
			getViewUserList();
		} else {
			System.out.println("请先选中一行");
		}

	}
	//插入新用户
	private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		Man_AddUser maUser = new Man_AddUser(new javax.swing.JFrame(), true);
		maUser.setVisible(true);
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnInsert;
	private javax.swing.JButton btnRefresh;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable tb_user;
	private javax.swing.JTextField txtUserName;
	// End of variables declaration//GEN-END:variables

}