/*
 * Man_AddUser.java
 *
 * Created on __DATE__, __TIME__
 */

package me.lazynight.stusys.view;

import java.awt.Image;
import java.io.IOException;

import javax.imageio.ImageIO;
import me.lazynight.stusys.entity.User;
import me.lazynight.stusys.service.ServiceFacade;

/**
 *
 * @author  __USER__
 */
public class Man_AddUser extends javax.swing.JDialog {

	/** Creates new form Man_AddUser */
	public Man_AddUser(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		//设置icon
		try {
			String src = "/img/users.png";
			Image image = ImageIO.read(this.getClass().getResource(src));
			this.setIconImage(image);
		} catch (IOException e) {
			e.printStackTrace();
		}
		//		//居中
		//		Dimension screensize = Toolkit.getDefaultToolkit().getScreenSize();
		//		Dimension framesize  = this.getSize();     
		//	    int x = (int)screensize.getWidth()/2 - (int)framesize.getWidth()/2;     
		//	    int y = (int)screensize.getHeight()/2 - (int)framesize.getHeight()/2;     
		//	    this.setLocation(x,y);
		setLocationRelativeTo(null);
		//禁止最大化
		this.setResizable(false);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		cmbPri = new javax.swing.JComboBox();
		txtUsername = new javax.swing.JTextField();
		txtPassword = new javax.swing.JPasswordField();
		jLabel3 = new javax.swing.JLabel();
		btnInsert = new javax.swing.JButton();
		btnExit = new javax.swing.JButton();
		lblMsg = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("\u6dfb\u52a0\u65b0\u7528\u6237");

		jLabel1.setText("\u7528\u6237\u540d\uff1a");

		jLabel2.setText("\u5bc6\u7801\uff1a");

		cmbPri.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"学生", "教师", "管理员" }));

		jLabel3.setText("\u6743\u9650\uff1a");

		btnInsert.setText("\u6dfb\u52a0");
		btnInsert.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnInsertActionPerformed(evt);
			}
		});

		btnExit.setText("\u53d6\u6d88");
		btnExit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnExitActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(jLabel2)
												.addComponent(jLabel3)
												.addComponent(jLabel1))
								.addGap(27, 27, 27)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		lblMsg)
																.addContainerGap())
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										btnInsert)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																										47,
																										Short.MAX_VALUE)
																								.addComponent(
																										btnExit,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										65,
																										javax.swing.GroupLayout.PREFERRED_SIZE))
																				.addComponent(
																						cmbPri,
																						0,
																						171,
																						Short.MAX_VALUE)
																				.addComponent(
																						txtPassword,
																						0,
																						0,
																						Short.MAX_VALUE)
																				.addComponent(
																						txtUsername,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						171,
																						Short.MAX_VALUE))
																.addContainerGap(
																		72,
																		Short.MAX_VALUE)))));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(42, 42, 42)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						txtUsername,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jLabel1))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						txtPassword,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jLabel2,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						18,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGap(32, 32,
																		32))
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(
																		cmbPri,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(
																		jLabel3)))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(btnInsert)
												.addComponent(btnExit))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(lblMsg)
								.addContainerGap(44, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String username = txtUsername.getText().trim();
		String password = txtPassword.getText().trim();
		String priname = cmbPri.getSelectedItem().toString();
		ServiceFacade sf = new ServiceFacade();
		User user = new User();
		user.setUsername(username);
		user.setPassword(password);
		if (priname == "学生") {
			user.setPrino(1);
		} else if (priname == "教师") {
			user.setPrino(2);
		} else {
			user.setPrino(3);
		}
		if (sf.insertUser(user)) {
			lblMsg.setText("添加成功");
		}else{
			lblMsg.setText("添加失败");
		}
	}

	private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.dispose();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				Man_AddUser dialog = new Man_AddUser(new javax.swing.JFrame(),
						true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnExit;
	private javax.swing.JButton btnInsert;
	private javax.swing.JComboBox cmbPri;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel lblMsg;
	private javax.swing.JPasswordField txtPassword;
	private javax.swing.JTextField txtUsername;
	// End of variables declaration//GEN-END:variables

}