/*
 * Man_Teachers.java
 *
 * Created on __DATE__, __TIME__
 */

package me.lazynight.stusys.view;

import me.lazynight.stusys.service.*;
import me.lazynight.stusys.entity.Teacher;
import me.lazynight.stusys.entity.ViewUser;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import javax.management.modelmbean.ModelMBean;

/**
 *
 * @author  __USER__
 */
public class Man_Teachers extends javax.swing.JPanel {

	/** Creates new form Man_Teachers */
	public Man_Teachers() {
		initComponents();
//		getTeacherList() ;
	}
	//获取教师列表
//	private void getTeacherList() {
//		ServiceFacade sf = new ServiceFacade();
//		List<Teacher> list = new ArrayList<Teacher>();
//		list = sf.getTeacherList();
//		//table
//		Object rowData[][] = new Object[list.size()][8];
//		String column[] = { "教师号", "姓名", "性别", "出生年月", "身份证", "家庭住址", "电话", "备注"};
//		tb_Teacher = new javax.swing.JTable(rowData, column);
//		jScrollPane1.setViewportView(tb_Teacher);
//		
//		int i = 0;
//		Iterator it = list.iterator();
//		while (it.hasNext()) {
//			Teacher t = (Teacher) it.next();
//			System.out.println(t);
//			rowData[i][0] = t.getId();
//			rowData[i][1] = t.getName();
//			rowData[i][2] = t.getSex();
//			rowData[i][3] = t.getYear();
//			rowData[i][4] = t.getIdcard();
//			rowData[i][5] = t.getAddress();
//			rowData[i][6] = t.getTel();
//			rowData[i][7] = t.getOther();
//			i++;
//		}
//	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tb_Teacher = new javax.swing.JTable();
		jPanel2 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		btnSelect = new javax.swing.JButton();
		txtTeaId = new javax.swing.JTextField();
		btnDelete = new javax.swing.JButton();
		btnInsert = new javax.swing.JButton();
		btnUpdate = new javax.swing.JButton();

		tb_Teacher.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "Title 1",
						"Title 2", "Title 3", "Title 4" }));
		jScrollPane1.setViewportView(tb_Teacher);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500,
				Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 323,
				Short.MAX_VALUE));

		jLabel1.setText("\u6559\u5e08\u53f7:");

		btnSelect.setText("\u67e5\u8be2");

		btnDelete.setText("\u5220\u9664");

		btnInsert.setText("\u63d2\u5165");

		btnUpdate.setText("\u66f4\u65b0");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jLabel1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												txtTeaId,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												117,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(btnSelect)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												btnInsert,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												60,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(btnDelete)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												btnUpdate,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												62,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(41, Short.MAX_VALUE)));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(btnSelect)
														.addComponent(
																txtTeaId,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(btnInsert)
														.addComponent(btnDelete)
														.addComponent(btnUpdate))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(jPanel1,
						javax.swing.GroupLayout.Alignment.TRAILING,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addComponent(jPanel2,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(jPanel1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)));
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnDelete;
	private javax.swing.JButton btnInsert;
	private javax.swing.JButton btnSelect;
	private javax.swing.JButton btnUpdate;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable tb_Teacher;
	private javax.swing.JTextField txtTeaId;
	// End of variables declaration//GEN-END:variables

}