/*
 * Man_Index.java
 *
 * Created on __DATE__, __TIME__
 */

package me.lazynight.stusys.view;

import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;

import javax.imageio.ImageIO;
import javax.swing.JComponent;

/**
 *
 * @author  __USER__
 */
public class Man_Index extends javax.swing.JFrame {

	/** Creates new form Man_Index */
	public Man_Index(int pri) {
		initComponents();
		setLocationRelativeTo(null);
		switch (pri) {
		case 1:
			lblPri.setText("学生");
			break;
		case 2:
			lblPri.setText("教师");
		case 3:
			lblPri.setText("管理员");
		default:
			break;
		}
		// 设置icon
		try {
			String src = "/img/users.png";
			Image image = ImageIO.read(this.getClass().getResource(src));
			this.setIconImage(image);
		} catch (IOException e) {
			e.printStackTrace();
		}
		this.setTitle("学生信息管理系统");
		refreshTime();
	}

	// 刷新状态栏时间
	public void refreshTime() {
		Timer timer = new Timer();
		TimerTask tt = new TimerTask() {
			public void run() {
				Date d = new Date();
				SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
				lblTime.setText(" 当前时间:" + s.format(d));// 显示系统日期时间
			}
		};
		timer.schedule(tt, 0, 1000);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		tabpane = new javax.swing.JTabbedPane();
		toolbar = new javax.swing.JToolBar();
		jLabel1 = new javax.swing.JLabel();
		lblPri = new javax.swing.JLabel();
		jSeparator1 = new javax.swing.JToolBar.Separator();
		jLabel2 = new javax.swing.JLabel();
		lblTime = new javax.swing.JLabel();
		menuBar = new javax.swing.JMenuBar();
		fileMenu = new javax.swing.JMenu();
		Man_Users = new javax.swing.JMenuItem();
		Man_Teachers = new javax.swing.JMenuItem();
		Man_Students = new javax.swing.JMenuItem();
		Man_Courses = new javax.swing.JMenuItem();
		Man_SelectCourses = new javax.swing.JMenuItem();
		Tea_GradeIn = new javax.swing.JMenuItem();
		Tea_Count = new javax.swing.JMenuItem();
		Stu_Grade = new javax.swing.JMenuItem();
		jSeparator2 = new javax.swing.JSeparator();
		Exit = new javax.swing.JMenuItem();
		helpMenu = new javax.swing.JMenu();
		aboutMenuItem = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		toolbar.setFloatable(false);
		toolbar.setRollover(true);

		jLabel1.setText("\u6743\u9650\uff1a");
		toolbar.add(jLabel1);

		lblPri.setForeground(new java.awt.Color(255, 0, 51));
		lblPri.addInputMethodListener(new java.awt.event.InputMethodListener() {
			public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
			}

			public void inputMethodTextChanged(
					java.awt.event.InputMethodEvent evt) {
				lblPriInputMethodTextChanged(evt);
			}
		});
		toolbar.add(lblPri);
		toolbar.add(jSeparator1);

		jLabel2.setText("\u65f6\u95f4\uff1a");
		toolbar.add(jLabel2);
		toolbar.add(lblTime);

		fileMenu.setText("\u529f\u80fd");

		Man_Users.setText("\u7528\u6237\u7ba1\u7406");
		Man_Users.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Man_UsersActionPerformed(evt);
			}
		});
		fileMenu.add(Man_Users);

		Man_Teachers.setText("\u6559\u5e08\u7ba1\u7406");
		Man_Teachers.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Man_TeachersActionPerformed(evt);
			}
		});
		fileMenu.add(Man_Teachers);

		Man_Students.setText("\u5b66\u751f\u7ba1\u7406");
		Man_Students.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Man_StudentsActionPerformed(evt);
			}
		});
		fileMenu.add(Man_Students);

		Man_Courses.setText("\u8bfe\u7a0b\u7ba1\u7406");
		Man_Courses.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Man_CoursesActionPerformed(evt);
			}
		});
		fileMenu.add(Man_Courses);

		Man_SelectCourses.setText("\u9009\u8bfe\u7ba1\u7406");
		Man_SelectCourses
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						Man_SelectCoursesActionPerformed(evt);
					}
				});
		fileMenu.add(Man_SelectCourses);

		Tea_GradeIn.setText("\u6210\u7ee9\u5f55\u5165");
		Tea_GradeIn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Tea_GradeInActionPerformed(evt);
			}
		});
		fileMenu.add(Tea_GradeIn);

		Tea_Count.setText("\u6210\u7ee9\u7edf\u8ba1");
		Tea_Count.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Tea_CountActionPerformed(evt);
			}
		});
		fileMenu.add(Tea_Count);

		Stu_Grade.setText("\u6210\u7ee9\u67e5\u8be2");
		Stu_Grade.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Stu_GradeActionPerformed(evt);
			}
		});
		fileMenu.add(Stu_Grade);
		fileMenu.add(jSeparator2);

		Exit.setText("\u9000\u51fa");
		Exit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ExitActionPerformed(evt);
			}
		});
		fileMenu.add(Exit);

		menuBar.add(fileMenu);

		helpMenu.setText("\u5e2e\u52a9");

		aboutMenuItem.setText("\u5173\u4e8e");
		aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				aboutMenuItemActionPerformed(evt);
			}
		});
		helpMenu.add(aboutMenuItem);

		menuBar.add(helpMenu);

		setJMenuBar(menuBar);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(toolbar, javax.swing.GroupLayout.DEFAULT_SIZE,
						571, Short.MAX_VALUE)
				.addComponent(tabpane, javax.swing.GroupLayout.DEFAULT_SIZE,
						571, Short.MAX_VALUE));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addComponent(tabpane,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										346,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(toolbar,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										25,
										javax.swing.GroupLayout.PREFERRED_SIZE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void Stu_GradeActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		Stu_Grade stu_grade = new Stu_Grade();
		tabpane.add("成绩查询", stu_grade);
		tabpane.setMnemonicAt(0, KeyEvent.VK_8);
	}

	private void Tea_CountActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		Tea_Count tea_count = new Tea_Count();
		tabpane.add("成绩统计", tea_count);
		tabpane.setMnemonicAt(0, KeyEvent.VK_7);
	}

	private void Tea_GradeInActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		Tea_GradeIn tea_gradein = new Tea_GradeIn();
		tabpane.add("成绩录入", tea_gradein);
		tabpane.setMnemonicAt(0, KeyEvent.VK_6);
	}

	//GEN-END:initComponents

	private void Man_SelectCoursesActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		Man_SelectCourses man_selectcources = new Man_SelectCourses();
		tabpane.add("选课管理", man_selectcources);
		tabpane.setMnemonicAt(0, KeyEvent.VK_5);
	}

	private void ExitActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		System.exit(0);
	}

	private void Man_CoursesActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		Man_Courses man_cources = new Man_Courses();
		tabpane.add("课程管理", man_cources);
		tabpane.setMnemonicAt(0, KeyEvent.VK_4);
	}

	private void Man_StudentsActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		Man_Students man_students = new Man_Students();
		tabpane.add("学生管理", man_students);
		tabpane.setMnemonicAt(0, KeyEvent.VK_3);
	}

	private void Man_TeachersActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		Man_Teachers man_teachers = new Man_Teachers();
		tabpane.add("教师管理", man_teachers);
		tabpane.setMnemonicAt(0, KeyEvent.VK_2);
	}

	private void Man_UsersActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		Man_Users man_users = new Man_Users();
		tabpane.addTab("用户管理", man_users);
		tabpane.setMnemonicAt(0, KeyEvent.VK_1);
	}

	private void lblPriInputMethodTextChanged(
			java.awt.event.InputMethodEvent evt) {
		// TODO add your handling code here:
	}

	private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		About about = new About(new javax.swing.JFrame(), true);
		about.setVisible(true);
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JMenuItem Exit;
	private javax.swing.JMenuItem Man_Courses;
	private javax.swing.JMenuItem Man_SelectCourses;
	private javax.swing.JMenuItem Man_Students;
	private javax.swing.JMenuItem Man_Teachers;
	private javax.swing.JMenuItem Man_Users;
	private javax.swing.JMenuItem Stu_Grade;
	private javax.swing.JMenuItem Tea_Count;
	private javax.swing.JMenuItem Tea_GradeIn;
	private javax.swing.JMenuItem aboutMenuItem;
	private javax.swing.JMenu fileMenu;
	private javax.swing.JMenu helpMenu;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JToolBar.Separator jSeparator1;
	private javax.swing.JSeparator jSeparator2;
	private javax.swing.JLabel lblPri;
	private javax.swing.JLabel lblTime;
	private javax.swing.JMenuBar menuBar;
	private javax.swing.JTabbedPane tabpane;
	private javax.swing.JToolBar toolbar;
	// End of variables declaration//GEN-END:variables

}